name: titan
description: Titan Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.10+110

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #https://plugins.jetbrains.com/plugin/10128-flutter-i18n
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  #https://github.com/flutterchina/dio
  dio: ^3.0.7
  #https://pub.dev/packages/package_info
  package_info: ^0.4.0+4
  #https://github.com/baseflowit/flutter-permission-handler
  permission_handler: ^5.0.0+hotfix.3
  #https://pub.dev/packages/event_bus#-installing-tab-
  event_bus: ^1.1.1
  #https://pub.dev/packages/fluttertoast
  fluttertoast: ^4.0.1
  #  flutter_webview_plugin: ^0.3.5
  #https://github:com/dnfield/flutter_svg:
  flutter_svg: ^0.17.3
  #https://pub.dev/packages/in_app_purchase#-installing-tab-
  #  in_app_purchase: 0.2.2+2
  #https://github.com/apptreesoftware/flutter_barcode_reader
  #  barcode_scan: ^1.0.0
  #https://pub.dev/packages/path_provider#-installing-tab-
  path_provider: ^1.6.5
  #https://pub.dev/packages/qr_flutter#-installing-tab-
  qr_flutter: ^3.2.0
  #https://pub.dev/packages/sqflite#-installing-tab-
  sqflite: ^1.3.0
  #https://pub.dev/packages/shared_preferences#-installing-tab-
  shared_preferences: ^0.5.6
  #https://pub.dev/packages/flutter_bloc
  #  flutter_bloc: ^3.2.0
  flutter_bloc: ^4.0.1
  #https://pub.dev/packages/equatable#-readme-tab-
  equatable: ^1.1.1
  #https://pub.dev/packages/logger#-installing-tab-
  logger: ^0.8.3
  #https://pub.dev/packages/flutter_statusbarcolor#-installing-tab-
  #  flutter_statusbarcolor: ^0.2.3
  #https://github.com/dart-lang/json_serializable
  #  json_annotation: ^2.4.0
  #https://pub.dev/packages/esys_flutter_share
  esys_flutter_share: 1.0.2
  #https://pub.dev/packages/uni_links
  uni_links: 0.2.0
  #https://pub.dev/packages/intro_slider#demo:
  intro_slider: ^2.2.6
  #https://pub.dev/packages/barcode_scan
  barcode_scan: 2.0.1
  #https://pub.dev/packages/flutter_downloader/versions/0.0.6#-installing-tab-
  #flutter_downloader: ^1.1.7
  #https://pub.dev/packages/flutter_html:
  flutter_html: ^0.11.0
  #https://pub.dev/packages/sprintf
  sprintf: ^4.0.2
  #https://github.com/tobrun/flutter-mapbox-gl
  mapbox_gl:
    path: ../mapbox_flutter
  #https://pub.dev/packages/floor
  floor: ^0.8.0
  #https://pub.dev/packages/rxdart
  rxdart: ^0.23.1
  #https://pub.dev/packages/url_launcher
  url_launcher: 5.1.2
  decimal: ^0.3.5
  #https://pub.dev/packages/carousel_pro
  carousel_pro: ^1.0.0
  web3dart: ^1.2.3
  bip39: ^1.0.3
  intl: ^0.16.0
  webview_flutter: ^0.3.20+2
  pull_to_refresh: ^1.5.7
  carousel_slider: ^1.3.1
  fake_cookie_manager: ^0.1.0
  loading: ^1.0.1
  flutter_inappwebview: ^3.1.0
  #  characters: ^0.5.0
  characters: ^1.0.0

  #  flutter_inappwebview:
  #    git:
  #      url: https://github.com/pichillilorenzo/flutter_inappwebview
  #https://pub.flutter-io.cn/packages/flutter_bugly
  flutter_bugly: ^0.2.8
  #    git:
  #      url: git@github.com:moyaying/flutter_bugly.git
  android_intent: ^0.3.4
  app_settings: ^3.0.0
  fluro: ^1.5.1
  #https://pub:dev/packages/image_pickers#-readme-tab-
#  image_pickers:
#    git:
#      url: git@github.com:moyaying/image_pickers.git
  image_pickers: ^1.0.7+6

  bordered_text: ^1.0.0
  #  video_player: ^0.10.8+1
  #  https://pub:dev/packages/flutter_echarts#-installing-tab-
  flutter_echarts: ^1.3.0
  #  multi_image_picker: ^4.6.7
  #  flutter_absolute_path: ^1.0.6
  #  flutter_native_image: ^0.0.5
  r_scan: ^0.1.4+1
  #  https://pub:dev/packages/flutter_widget_from_html_core#-installing-tab-:
  flutter_widget_from_html_core: ^0.3.3

  # https://pub.dev/packages/local_auth
  local_auth: 0.6.2+3
  # https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: 3.3.3
  # https://pub.dev/packages/gesture_unlock
  gesture_unlock: ^0.0.1
  # https://pub.dev/packages/pin_input_text_field
  pin_input_text_field: 3.0.3
  # https://pub.dev/packages/image_save
  image_save: 3.1.1
  # https://pub.dev/packages/vibration
  vibration: 1.4.0
  #https://pub.dev/packages/oktoast
  oktoast: ^2.3.2
  flutter_recaptcha_v2:
    git:
      url: git@github.com:hyperion-hyn/flutter_recaptcha_v2.git


dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.2
  json_serializable: ^3.2.5
  #  floor_generator: ^0.9.0

  #https://github.com/dart-lang/mockito
  mockito: ^4.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - res/drawable/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: iconfont
      fonts:
        - asset: res/fonts/iconfont.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
