// Objective-C API for talking to github.com/hyperion-hyn/re-encrypt-server/mobile Go package.
//   gobind -lang=objc github.com/hyperion-hyn/re-encrypt-server/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileCipher;

@interface MobileCipher : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)decrypt:(NSString*)prvStr cipherText:(NSString*)cipherText;
- (NSString*)encrypt:(NSString*)pubStr message:(NSString*)message;
- (NSString*)genKeyPair;
@end

FOUNDATION_EXPORT MobileCipher* MobileNewCipher(void);

#endif
