// Objective-C API for talking to github.com/hyperion-hyn/re-encrypt-server/mobile Go package.
//   gobind -lang=objc github.com/hyperion-hyn/re-encrypt-server/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileCipher;

@interface MobileCipher : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
- (NSString* _Nonnull)deCompressPubkey:(NSString* _Nullable)pubStrC;
- (NSString* _Nonnull)decrypt:(NSString* _Nullable)prvStr cipherText:(NSString* _Nullable)cipherText;
- (NSString* _Nonnull)encrypt:(NSString* _Nullable)pubStr message:(NSString* _Nullable)message;
- (NSString* _Nonnull)genKeyPair;
@end

FOUNDATION_EXPORT MobileCipher* _Nullable MobileNewCipher(void);

#endif
