
// Objective-C API for talking to the following Go packages
//
//	github.com/ethereum/go-ethereum/mobile_lib
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mobile_lib_FRAMEWORK_H__
#define __Mobile_lib_FRAMEWORK_H__

#include "Mobile_lib.objc.h"
#include "Universe.objc.h"

#endif
