// Objective-C API for talking to github.com/ethereum/go-ethereum/mobile_lib Go package.
//   gobind -lang=objc github.com/ethereum/go-ethereum/mobile_lib
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_lib_H__
#define __Mobile_lib_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class Mobile_libAddressLib;
@class Mobile_libCipherLib;

@interface Mobile_libAddressLib : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
- (NSString* _Nonnull)publicKeyToEthAddress:(NSString* _Nullable)pubStr;
- (NSString* _Nonnull)publicKeyToHynAddress:(NSString* _Nullable)pubStr isMainNet:(BOOL)isMainNet;
@end

@interface Mobile_libCipherLib : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSString* _Nonnull)deCompressPubkey:(NSString* _Nullable)pubStrC;
- (NSString* _Nonnull)decrypt:(NSString* _Nullable)prvStr cipherText:(NSString* _Nullable)cipherText;
- (NSString* _Nonnull)encrypt:(NSString* _Nullable)pubStr message:(NSString* _Nullable)message;
- (NSString* _Nonnull)genKeyPair;
@end

FOUNDATION_EXPORT Mobile_libAddressLib* _Nullable Mobile_libNewAddressLib(void);

FOUNDATION_EXPORT Mobile_libCipherLib* _Nullable Mobile_libNewCipher(void);

#endif
